### ISSUE TITLE
Unable to download fbank.zip

### ISSUE THREAD

**Issue by tetsucafe** [choyingw/Cross-Modal-Perceptionist#7]
Thanks for the great work!
It seems that the download link for the voice data (fbank.zip) is broken in the shared data (probably due to the number of downloads). Could you please make a copy and share it again?
I need it for my research.
Thank you very much!

**Comment by DepthComputation** [comment]
Hi this is the alternative link from CMU's author for fbank.zip

https://drive.google.com/open?id=1T5Mv_7FC2ZfrjQu17Rn9E24IOgdii4tj

**Comment by tetsucafe** [comment]
Thanks for the response @DepthComputation !
I already tried that link, but it seems to be having the same problem and not downloading.
Can you do me a favor and do one of the following?

∙ Share your link (if you have saved fbank.zip in the past)

・Check if you can install it with the current link.
[This project's](https://drive.google.com/file/d/1Ac6b3oDB1Ot274u4CU-OaeSlUT5r6bZK/view)
[CMU's](https://drive.google.com/open?id=1T5Mv_7FC2ZfrjQu17Rn9E24IOgdii4tj)

Thanks so much!

**Comment by DepthComputation** [comment]
@tetsucafe I can successfully download via both of the link. What does the error message show on your side? Or do you have screenshots? Thanks

**Comment by tetsucafe** [comment]
@DepthComputation 
I was always getting error messages like the screenshot below, but I tried today and was able to download successfully. there seems to be a monthly limit on the number of downloads from google drive.
Thank you for responding. I appreciate you very much.
<img width="1415" alt="Google_ドライブ_-_容量を超えています" src="https://github.com/choyingw/Cross-Modal-Perceptionist/assets/72336987/53e6d87b-3a72-47e2-8170-3c2b6107840c">
